// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

public interface AnimalProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:handin3.AnimalProducts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  java.util.List<via.sdj3.handin3.PackageId> 
      getPackageIdList();
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  via.sdj3.handin3.PackageId getPackageId(int index);
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  int getPackageIdCount();
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  java.util.List<? extends via.sdj3.handin3.PackageIdOrBuilder> 
      getPackageIdOrBuilderList();
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  via.sdj3.handin3.PackageIdOrBuilder getPackageIdOrBuilder(
      int index);

  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  java.util.List<via.sdj3.handin3.HalfAnAnimalId> 
      getHalfAnAnimalIdList();
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  via.sdj3.handin3.HalfAnAnimalId getHalfAnAnimalId(int index);
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  int getHalfAnAnimalIdCount();
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  java.util.List<? extends via.sdj3.handin3.HalfAnAnimalIdOrBuilder> 
      getHalfAnAnimalIdOrBuilderList();
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  via.sdj3.handin3.HalfAnAnimalIdOrBuilder getHalfAnAnimalIdOrBuilder(
      int index);
}
