// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

/**
 * Protobuf type {@code handin3.AnimalProducts}
 */
public final class AnimalProducts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:handin3.AnimalProducts)
    AnimalProductsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalProducts.newBuilder() to construct.
  private AnimalProducts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalProducts() {
    packageId_ = java.util.Collections.emptyList();
    halfAnAnimalId_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnimalProducts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalProducts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              packageId_ = new java.util.ArrayList<via.sdj3.handin3.PackageId>();
              mutable_bitField0_ |= 0x00000001;
            }
            packageId_.add(
                input.readMessage(via.sdj3.handin3.PackageId.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              halfAnAnimalId_ = new java.util.ArrayList<via.sdj3.handin3.HalfAnAnimalId>();
              mutable_bitField0_ |= 0x00000002;
            }
            halfAnAnimalId_.add(
                input.readMessage(via.sdj3.handin3.HalfAnAnimalId.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        packageId_ = java.util.Collections.unmodifiableList(packageId_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        halfAnAnimalId_ = java.util.Collections.unmodifiableList(halfAnAnimalId_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.handin3.Services.internal_static_handin3_AnimalProducts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.handin3.Services.internal_static_handin3_AnimalProducts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.handin3.AnimalProducts.class, via.sdj3.handin3.AnimalProducts.Builder.class);
  }

  public static final int PACKAGEID_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.handin3.PackageId> packageId_;
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.handin3.PackageId> getPackageIdList() {
    return packageId_;
  }
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.handin3.PackageIdOrBuilder> 
      getPackageIdOrBuilderList() {
    return packageId_;
  }
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  @java.lang.Override
  public int getPackageIdCount() {
    return packageId_.size();
  }
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.handin3.PackageId getPackageId(int index) {
    return packageId_.get(index);
  }
  /**
   * <code>repeated .handin3.PackageId packageId = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.handin3.PackageIdOrBuilder getPackageIdOrBuilder(
      int index) {
    return packageId_.get(index);
  }

  public static final int HALFANANIMALID_FIELD_NUMBER = 2;
  private java.util.List<via.sdj3.handin3.HalfAnAnimalId> halfAnAnimalId_;
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.handin3.HalfAnAnimalId> getHalfAnAnimalIdList() {
    return halfAnAnimalId_;
  }
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.handin3.HalfAnAnimalIdOrBuilder> 
      getHalfAnAnimalIdOrBuilderList() {
    return halfAnAnimalId_;
  }
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  @java.lang.Override
  public int getHalfAnAnimalIdCount() {
    return halfAnAnimalId_.size();
  }
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  @java.lang.Override
  public via.sdj3.handin3.HalfAnAnimalId getHalfAnAnimalId(int index) {
    return halfAnAnimalId_.get(index);
  }
  /**
   * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
   */
  @java.lang.Override
  public via.sdj3.handin3.HalfAnAnimalIdOrBuilder getHalfAnAnimalIdOrBuilder(
      int index) {
    return halfAnAnimalId_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < packageId_.size(); i++) {
      output.writeMessage(1, packageId_.get(i));
    }
    for (int i = 0; i < halfAnAnimalId_.size(); i++) {
      output.writeMessage(2, halfAnAnimalId_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < packageId_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, packageId_.get(i));
    }
    for (int i = 0; i < halfAnAnimalId_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, halfAnAnimalId_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.handin3.AnimalProducts)) {
      return super.equals(obj);
    }
    via.sdj3.handin3.AnimalProducts other = (via.sdj3.handin3.AnimalProducts) obj;

    if (!getPackageIdList()
        .equals(other.getPackageIdList())) return false;
    if (!getHalfAnAnimalIdList()
        .equals(other.getHalfAnAnimalIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPackageIdCount() > 0) {
      hash = (37 * hash) + PACKAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getPackageIdList().hashCode();
    }
    if (getHalfAnAnimalIdCount() > 0) {
      hash = (37 * hash) + HALFANANIMALID_FIELD_NUMBER;
      hash = (53 * hash) + getHalfAnAnimalIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.handin3.AnimalProducts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.handin3.AnimalProducts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.handin3.AnimalProducts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.handin3.AnimalProducts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.handin3.AnimalProducts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code handin3.AnimalProducts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:handin3.AnimalProducts)
      via.sdj3.handin3.AnimalProductsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.handin3.Services.internal_static_handin3_AnimalProducts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.handin3.Services.internal_static_handin3_AnimalProducts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.handin3.AnimalProducts.class, via.sdj3.handin3.AnimalProducts.Builder.class);
    }

    // Construct using via.sdj3.handin3.AnimalProducts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPackageIdFieldBuilder();
        getHalfAnAnimalIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (packageIdBuilder_ == null) {
        packageId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        packageIdBuilder_.clear();
      }
      if (halfAnAnimalIdBuilder_ == null) {
        halfAnAnimalId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        halfAnAnimalIdBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.handin3.Services.internal_static_handin3_AnimalProducts_descriptor;
    }

    @java.lang.Override
    public via.sdj3.handin3.AnimalProducts getDefaultInstanceForType() {
      return via.sdj3.handin3.AnimalProducts.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.handin3.AnimalProducts build() {
      via.sdj3.handin3.AnimalProducts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.handin3.AnimalProducts buildPartial() {
      via.sdj3.handin3.AnimalProducts result = new via.sdj3.handin3.AnimalProducts(this);
      int from_bitField0_ = bitField0_;
      if (packageIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          packageId_ = java.util.Collections.unmodifiableList(packageId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.packageId_ = packageId_;
      } else {
        result.packageId_ = packageIdBuilder_.build();
      }
      if (halfAnAnimalIdBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          halfAnAnimalId_ = java.util.Collections.unmodifiableList(halfAnAnimalId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.halfAnAnimalId_ = halfAnAnimalId_;
      } else {
        result.halfAnAnimalId_ = halfAnAnimalIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.handin3.AnimalProducts) {
        return mergeFrom((via.sdj3.handin3.AnimalProducts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.handin3.AnimalProducts other) {
      if (other == via.sdj3.handin3.AnimalProducts.getDefaultInstance()) return this;
      if (packageIdBuilder_ == null) {
        if (!other.packageId_.isEmpty()) {
          if (packageId_.isEmpty()) {
            packageId_ = other.packageId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePackageIdIsMutable();
            packageId_.addAll(other.packageId_);
          }
          onChanged();
        }
      } else {
        if (!other.packageId_.isEmpty()) {
          if (packageIdBuilder_.isEmpty()) {
            packageIdBuilder_.dispose();
            packageIdBuilder_ = null;
            packageId_ = other.packageId_;
            bitField0_ = (bitField0_ & ~0x00000001);
            packageIdBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPackageIdFieldBuilder() : null;
          } else {
            packageIdBuilder_.addAllMessages(other.packageId_);
          }
        }
      }
      if (halfAnAnimalIdBuilder_ == null) {
        if (!other.halfAnAnimalId_.isEmpty()) {
          if (halfAnAnimalId_.isEmpty()) {
            halfAnAnimalId_ = other.halfAnAnimalId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHalfAnAnimalIdIsMutable();
            halfAnAnimalId_.addAll(other.halfAnAnimalId_);
          }
          onChanged();
        }
      } else {
        if (!other.halfAnAnimalId_.isEmpty()) {
          if (halfAnAnimalIdBuilder_.isEmpty()) {
            halfAnAnimalIdBuilder_.dispose();
            halfAnAnimalIdBuilder_ = null;
            halfAnAnimalId_ = other.halfAnAnimalId_;
            bitField0_ = (bitField0_ & ~0x00000002);
            halfAnAnimalIdBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHalfAnAnimalIdFieldBuilder() : null;
          } else {
            halfAnAnimalIdBuilder_.addAllMessages(other.halfAnAnimalId_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.handin3.AnimalProducts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.handin3.AnimalProducts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.handin3.PackageId> packageId_ =
      java.util.Collections.emptyList();
    private void ensurePackageIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        packageId_ = new java.util.ArrayList<via.sdj3.handin3.PackageId>(packageId_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.handin3.PackageId, via.sdj3.handin3.PackageId.Builder, via.sdj3.handin3.PackageIdOrBuilder> packageIdBuilder_;

    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public java.util.List<via.sdj3.handin3.PackageId> getPackageIdList() {
      if (packageIdBuilder_ == null) {
        return java.util.Collections.unmodifiableList(packageId_);
      } else {
        return packageIdBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public int getPackageIdCount() {
      if (packageIdBuilder_ == null) {
        return packageId_.size();
      } else {
        return packageIdBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public via.sdj3.handin3.PackageId getPackageId(int index) {
      if (packageIdBuilder_ == null) {
        return packageId_.get(index);
      } else {
        return packageIdBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder setPackageId(
        int index, via.sdj3.handin3.PackageId value) {
      if (packageIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackageIdIsMutable();
        packageId_.set(index, value);
        onChanged();
      } else {
        packageIdBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder setPackageId(
        int index, via.sdj3.handin3.PackageId.Builder builderForValue) {
      if (packageIdBuilder_ == null) {
        ensurePackageIdIsMutable();
        packageId_.set(index, builderForValue.build());
        onChanged();
      } else {
        packageIdBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder addPackageId(via.sdj3.handin3.PackageId value) {
      if (packageIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackageIdIsMutable();
        packageId_.add(value);
        onChanged();
      } else {
        packageIdBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder addPackageId(
        int index, via.sdj3.handin3.PackageId value) {
      if (packageIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePackageIdIsMutable();
        packageId_.add(index, value);
        onChanged();
      } else {
        packageIdBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder addPackageId(
        via.sdj3.handin3.PackageId.Builder builderForValue) {
      if (packageIdBuilder_ == null) {
        ensurePackageIdIsMutable();
        packageId_.add(builderForValue.build());
        onChanged();
      } else {
        packageIdBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder addPackageId(
        int index, via.sdj3.handin3.PackageId.Builder builderForValue) {
      if (packageIdBuilder_ == null) {
        ensurePackageIdIsMutable();
        packageId_.add(index, builderForValue.build());
        onChanged();
      } else {
        packageIdBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder addAllPackageId(
        java.lang.Iterable<? extends via.sdj3.handin3.PackageId> values) {
      if (packageIdBuilder_ == null) {
        ensurePackageIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, packageId_);
        onChanged();
      } else {
        packageIdBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder clearPackageId() {
      if (packageIdBuilder_ == null) {
        packageId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        packageIdBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public Builder removePackageId(int index) {
      if (packageIdBuilder_ == null) {
        ensurePackageIdIsMutable();
        packageId_.remove(index);
        onChanged();
      } else {
        packageIdBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public via.sdj3.handin3.PackageId.Builder getPackageIdBuilder(
        int index) {
      return getPackageIdFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public via.sdj3.handin3.PackageIdOrBuilder getPackageIdOrBuilder(
        int index) {
      if (packageIdBuilder_ == null) {
        return packageId_.get(index);  } else {
        return packageIdBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public java.util.List<? extends via.sdj3.handin3.PackageIdOrBuilder> 
         getPackageIdOrBuilderList() {
      if (packageIdBuilder_ != null) {
        return packageIdBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(packageId_);
      }
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public via.sdj3.handin3.PackageId.Builder addPackageIdBuilder() {
      return getPackageIdFieldBuilder().addBuilder(
          via.sdj3.handin3.PackageId.getDefaultInstance());
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public via.sdj3.handin3.PackageId.Builder addPackageIdBuilder(
        int index) {
      return getPackageIdFieldBuilder().addBuilder(
          index, via.sdj3.handin3.PackageId.getDefaultInstance());
    }
    /**
     * <code>repeated .handin3.PackageId packageId = 1;</code>
     */
    public java.util.List<via.sdj3.handin3.PackageId.Builder> 
         getPackageIdBuilderList() {
      return getPackageIdFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.handin3.PackageId, via.sdj3.handin3.PackageId.Builder, via.sdj3.handin3.PackageIdOrBuilder> 
        getPackageIdFieldBuilder() {
      if (packageIdBuilder_ == null) {
        packageIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.handin3.PackageId, via.sdj3.handin3.PackageId.Builder, via.sdj3.handin3.PackageIdOrBuilder>(
                packageId_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        packageId_ = null;
      }
      return packageIdBuilder_;
    }

    private java.util.List<via.sdj3.handin3.HalfAnAnimalId> halfAnAnimalId_ =
      java.util.Collections.emptyList();
    private void ensureHalfAnAnimalIdIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        halfAnAnimalId_ = new java.util.ArrayList<via.sdj3.handin3.HalfAnAnimalId>(halfAnAnimalId_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.handin3.HalfAnAnimalId, via.sdj3.handin3.HalfAnAnimalId.Builder, via.sdj3.handin3.HalfAnAnimalIdOrBuilder> halfAnAnimalIdBuilder_;

    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public java.util.List<via.sdj3.handin3.HalfAnAnimalId> getHalfAnAnimalIdList() {
      if (halfAnAnimalIdBuilder_ == null) {
        return java.util.Collections.unmodifiableList(halfAnAnimalId_);
      } else {
        return halfAnAnimalIdBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public int getHalfAnAnimalIdCount() {
      if (halfAnAnimalIdBuilder_ == null) {
        return halfAnAnimalId_.size();
      } else {
        return halfAnAnimalIdBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public via.sdj3.handin3.HalfAnAnimalId getHalfAnAnimalId(int index) {
      if (halfAnAnimalIdBuilder_ == null) {
        return halfAnAnimalId_.get(index);
      } else {
        return halfAnAnimalIdBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder setHalfAnAnimalId(
        int index, via.sdj3.handin3.HalfAnAnimalId value) {
      if (halfAnAnimalIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.set(index, value);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder setHalfAnAnimalId(
        int index, via.sdj3.handin3.HalfAnAnimalId.Builder builderForValue) {
      if (halfAnAnimalIdBuilder_ == null) {
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.set(index, builderForValue.build());
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder addHalfAnAnimalId(via.sdj3.handin3.HalfAnAnimalId value) {
      if (halfAnAnimalIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.add(value);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder addHalfAnAnimalId(
        int index, via.sdj3.handin3.HalfAnAnimalId value) {
      if (halfAnAnimalIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.add(index, value);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder addHalfAnAnimalId(
        via.sdj3.handin3.HalfAnAnimalId.Builder builderForValue) {
      if (halfAnAnimalIdBuilder_ == null) {
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.add(builderForValue.build());
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder addHalfAnAnimalId(
        int index, via.sdj3.handin3.HalfAnAnimalId.Builder builderForValue) {
      if (halfAnAnimalIdBuilder_ == null) {
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.add(index, builderForValue.build());
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder addAllHalfAnAnimalId(
        java.lang.Iterable<? extends via.sdj3.handin3.HalfAnAnimalId> values) {
      if (halfAnAnimalIdBuilder_ == null) {
        ensureHalfAnAnimalIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, halfAnAnimalId_);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder clearHalfAnAnimalId() {
      if (halfAnAnimalIdBuilder_ == null) {
        halfAnAnimalId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public Builder removeHalfAnAnimalId(int index) {
      if (halfAnAnimalIdBuilder_ == null) {
        ensureHalfAnAnimalIdIsMutable();
        halfAnAnimalId_.remove(index);
        onChanged();
      } else {
        halfAnAnimalIdBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public via.sdj3.handin3.HalfAnAnimalId.Builder getHalfAnAnimalIdBuilder(
        int index) {
      return getHalfAnAnimalIdFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public via.sdj3.handin3.HalfAnAnimalIdOrBuilder getHalfAnAnimalIdOrBuilder(
        int index) {
      if (halfAnAnimalIdBuilder_ == null) {
        return halfAnAnimalId_.get(index);  } else {
        return halfAnAnimalIdBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public java.util.List<? extends via.sdj3.handin3.HalfAnAnimalIdOrBuilder> 
         getHalfAnAnimalIdOrBuilderList() {
      if (halfAnAnimalIdBuilder_ != null) {
        return halfAnAnimalIdBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(halfAnAnimalId_);
      }
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public via.sdj3.handin3.HalfAnAnimalId.Builder addHalfAnAnimalIdBuilder() {
      return getHalfAnAnimalIdFieldBuilder().addBuilder(
          via.sdj3.handin3.HalfAnAnimalId.getDefaultInstance());
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public via.sdj3.handin3.HalfAnAnimalId.Builder addHalfAnAnimalIdBuilder(
        int index) {
      return getHalfAnAnimalIdFieldBuilder().addBuilder(
          index, via.sdj3.handin3.HalfAnAnimalId.getDefaultInstance());
    }
    /**
     * <code>repeated .handin3.HalfAnAnimalId halfAnAnimalId = 2;</code>
     */
    public java.util.List<via.sdj3.handin3.HalfAnAnimalId.Builder> 
         getHalfAnAnimalIdBuilderList() {
      return getHalfAnAnimalIdFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.handin3.HalfAnAnimalId, via.sdj3.handin3.HalfAnAnimalId.Builder, via.sdj3.handin3.HalfAnAnimalIdOrBuilder> 
        getHalfAnAnimalIdFieldBuilder() {
      if (halfAnAnimalIdBuilder_ == null) {
        halfAnAnimalIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.handin3.HalfAnAnimalId, via.sdj3.handin3.HalfAnAnimalId.Builder, via.sdj3.handin3.HalfAnAnimalIdOrBuilder>(
                halfAnAnimalId_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        halfAnAnimalId_ = null;
      }
      return halfAnAnimalIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:handin3.AnimalProducts)
  }

  // @@protoc_insertion_point(class_scope:handin3.AnimalProducts)
  private static final via.sdj3.handin3.AnimalProducts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.handin3.AnimalProducts();
  }

  public static via.sdj3.handin3.AnimalProducts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalProducts>
      PARSER = new com.google.protobuf.AbstractParser<AnimalProducts>() {
    @java.lang.Override
    public AnimalProducts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalProducts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalProducts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalProducts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.handin3.AnimalProducts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

