// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

public interface RegistrationNumbersForAnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:handin3.RegistrationNumbersForAnimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .handin3.AnimalId ids = 1;</code>
   */
  java.util.List<via.sdj3.handin3.AnimalId> 
      getIdsList();
  /**
   * <code>repeated .handin3.AnimalId ids = 1;</code>
   */
  via.sdj3.handin3.AnimalId getIds(int index);
  /**
   * <code>repeated .handin3.AnimalId ids = 1;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated .handin3.AnimalId ids = 1;</code>
   */
  java.util.List<? extends via.sdj3.handin3.AnimalIdOrBuilder> 
      getIdsOrBuilderList();
  /**
   * <code>repeated .handin3.AnimalId ids = 1;</code>
   */
  via.sdj3.handin3.AnimalIdOrBuilder getIdsOrBuilder(
      int index);
}
