// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_PackageId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_PackageId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_RegistrationNumbersForAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_RegistrationNumbersForAnimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_HalfAnAnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_HalfAnAnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalProducts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalProducts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\007handin3\"\027\n\tPackageId\022\n" +
      "\n\002id\030\001 \001(\005\">\n\034RegistrationNumbersForAnim" +
      "al\022\036\n\003ids\030\001 \003(\0132\021.handin3.AnimalId\"\034\n\016Ha" +
      "lfAnAnimalId\022\n\n\002id\030\001 \001(\005\"\026\n\010AnimalId\022\n\n\002" +
      "id\030\001 \001(\005\"h\n\016AnimalProducts\022%\n\tpackageId\030" +
      "\001 \003(\0132\022.handin3.PackageId\022/\n\016halfAnAnima" +
      "lId\030\002 \003(\0132\027.handin3.HalfAnAnimalId2h\n$Ge" +
      "tAnimalsRegistrationNumbersPackage\022@\n\003Ge" +
      "t\022\022.handin3.PackageId\032%.handin3.Registra" +
      "tionNumbersForAnimal2j\n!GetAnimalsRegist" +
      "rationNumbersHalf\022E\n\003Get\022\027.handin3.HalfA" +
      "nAnimalId\032%.handin3.RegistrationNumbersF" +
      "orAnimal2F\n\021GetAnimalProducts\0221\n\003Get\022\021.h" +
      "andin3.AnimalId\032\027.handin3.AnimalProducts" +
      "B\024\n\020via.sdj3.handin3P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_handin3_PackageId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_handin3_PackageId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_PackageId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_RegistrationNumbersForAnimal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_handin3_RegistrationNumbersForAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_RegistrationNumbersForAnimal_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_handin3_HalfAnAnimalId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_handin3_HalfAnAnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_HalfAnAnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_AnimalId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_handin3_AnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_AnimalProducts_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_handin3_AnimalProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalProducts_descriptor,
        new java.lang.String[] { "PackageId", "HalfAnAnimalId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
