// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_PackageId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_PackageId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_Package_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_Package_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_HalfAnAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_HalfAnAnimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_RegistrationNumbersForAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_RegistrationNumbersForAnimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_HalfAnAnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_HalfAnAnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalProducts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalProducts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\007handin3\"$\n\006Animal\022\n\n\002i" +
      "d\030\001 \001(\005\022\016\n\006weight\030\002 \001(\001\"Y\n\nAnimalPart\022\n\n" +
      "\002id\030\001 \001(\005\022\016\n\006weight\030\002 \001(\001\022\014\n\004type\030\003 \001(\t\022" +
      "!\n\010cameFrom\030\004 \001(\0132\017.handin3.Animal\"\027\n\tPa" +
      "ckageId\022\n\n\002id\030\001 \001(\005\"[\n\007Package\022\036\n\002id\030\001 \001" +
      "(\0132\022.handin3.PackageId\022\014\n\004type\030\002 \001(\t\022\"\n\005" +
      "parts\030\003 \003(\0132\023.handin3.AnimalPart\"W\n\014Half" +
      "AnAnimal\022#\n\002id\030\001 \001(\0132\027.handin3.HalfAnAni" +
      "malId\022\"\n\005parts\030\002 \003(\0132\023.handin3.AnimalPar" +
      "t\">\n\034RegistrationNumbersForAnimal\022\036\n\003ids" +
      "\030\001 \003(\0132\021.handin3.AnimalId\"\034\n\016HalfAnAnima" +
      "lId\022\n\n\002id\030\001 \001(\005\"\026\n\010AnimalId\022\n\n\002id\030\001 \001(\005\"" +
      "h\n\016AnimalProducts\022%\n\tpackageId\030\001 \003(\0132\022.h" +
      "andin3.PackageId\022/\n\016halfAnAnimalId\030\002 \003(\013" +
      "2\027.handin3.HalfAnAnimalId2h\n$GetAnimalsR" +
      "egistrationNumbersPackage\022@\n\003Get\022\022.handi" +
      "n3.PackageId\032%.handin3.RegistrationNumbe" +
      "rsForAnimal2j\n!GetAnimalsRegistrationNum" +
      "bersHalf\022E\n\003Get\022\027.handin3.HalfAnAnimalId" +
      "\032%.handin3.RegistrationNumbersForAnimal2" +
      "F\n\021GetAnimalProducts\0221\n\003Get\022\021.handin3.An" +
      "imalId\032\027.handin3.AnimalProductsB\024\n\020via.s" +
      "dj3.handin3P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_handin3_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_handin3_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_Animal_descriptor,
        new java.lang.String[] { "Id", "Weight", });
    internal_static_handin3_AnimalPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_handin3_AnimalPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalPart_descriptor,
        new java.lang.String[] { "Id", "Weight", "Type", "CameFrom", });
    internal_static_handin3_PackageId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_handin3_PackageId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_PackageId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_Package_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_handin3_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_Package_descriptor,
        new java.lang.String[] { "Id", "Type", "Parts", });
    internal_static_handin3_HalfAnAnimal_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_handin3_HalfAnAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_HalfAnAnimal_descriptor,
        new java.lang.String[] { "Id", "Parts", });
    internal_static_handin3_RegistrationNumbersForAnimal_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_handin3_RegistrationNumbersForAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_RegistrationNumbersForAnimal_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_handin3_HalfAnAnimalId_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_handin3_HalfAnAnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_HalfAnAnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_AnimalId_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_handin3_AnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_AnimalProducts_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_handin3_AnimalProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalProducts_descriptor,
        new java.lang.String[] { "PackageId", "HalfAnAnimalId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
