// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package via.sdj3.handin3;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_AnimalPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_AnimalPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_PackageId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_PackageId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_Package_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_Package_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_HalfAnAnimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_HalfAnAnimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_handin3_HalfAnAnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_handin3_HalfAnAnimalId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\007handin3\"$\n\006Animal\022\n\n\002i" +
      "d\030\001 \001(\005\022\016\n\006weight\030\002 \001(\001\"Y\n\nAnimalPart\022\n\n" +
      "\002id\030\001 \001(\005\022\016\n\006weight\030\002 \001(\001\022\014\n\004type\030\003 \001(\t\022" +
      "!\n\010cameFrom\030\004 \001(\0132\017.handin3.Animal\"\027\n\tPa" +
      "ckageId\022\n\n\002id\030\001 \001(\005\"[\n\007Package\022\036\n\002id\030\001 \001" +
      "(\0132\022.handin3.PackageId\022\014\n\004type\030\002 \001(\t\022\"\n\005" +
      "parts\030\003 \003(\0132\023.handin3.AnimalPart\"W\n\014Half" +
      "AnAnimal\022#\n\002id\030\001 \001(\0132\027.handin3.HalfAnAni" +
      "malId\022\"\n\005parts\030\002 \003(\0132\023.handin3.AnimalPar" +
      "t\"\034\n\016HalfAnAnimalId\022\n\n\002id\030\001 \001(\0052S\n$GetAn" +
      "imalsRegistrationNumbersPackage\022+\n\003Get\022\022" +
      ".handin3.PackageId\032\020.handin3.Package2Z\n!" +
      "GetAnimalsRegistrationNumbersHalf\0225\n\003Get" +
      "\022\027.handin3.HalfAnAnimalId\032\025.handin3.Half" +
      "AnAnimalB\024\n\020via.sdj3.handin3P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_handin3_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_handin3_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_Animal_descriptor,
        new java.lang.String[] { "Id", "Weight", });
    internal_static_handin3_AnimalPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_handin3_AnimalPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_AnimalPart_descriptor,
        new java.lang.String[] { "Id", "Weight", "Type", "CameFrom", });
    internal_static_handin3_PackageId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_handin3_PackageId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_PackageId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_handin3_Package_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_handin3_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_Package_descriptor,
        new java.lang.String[] { "Id", "Type", "Parts", });
    internal_static_handin3_HalfAnAnimal_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_handin3_HalfAnAnimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_HalfAnAnimal_descriptor,
        new java.lang.String[] { "Id", "Parts", });
    internal_static_handin3_HalfAnAnimalId_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_handin3_HalfAnAnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_handin3_HalfAnAnimalId_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
